### ISSUE TITLE
Accessibility: Confetti animates and shouldn't when prefers-reduced-motion set

### ISSUE THREAD

**Issue by Betree** [catdad/canvas-confetti#114]
**Description**
Confetti animates regardless of [the prefers-reduced-motion media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion), causing site accessibility issues.

**Expected behavior**
Confetti probably shouldn't animate in multiple directions or at all when `prefers-reduced-motion` is set. See https://webkit.org/blog/7551/responsive-design-for-motion/ for some tips in designing for motion accessibility.

**Additional context**
This issue mostly copy-pasted from @iliana's https://github.com/opencollective/opencollective/issues/3036. The issue is very comprehensive and well documented, please look at it if you want more info. I wanted to open the discussion here to have a chance at fixing that for every one else using this library.

**Comment by catdad** [comment]
Thank you for bringing this to my attention!

I'd like to understand what is expected or precedented in this case for a library who's entire point is to create a chaotic animation. In this case, the animation is not an enhancement for the library, but is instead the entirety of the library.

While the blog and various other readings do tell you how to detect the issue, they also talk about how it is a case-by-case decision to figure out what to do. For example, the confetti could be celebratory like it is on opencollective, where it should removed for users that prefer less motion. But it may also be used in a storyline, where for example a confetti cannon is used to fill a bucket of confetti. In this case, removing it entirely breaks the story in an unexpected way. The decision I make has to fit all use cases.

Do you have an example of other libraries whose entire purpose is to perform an animation taking on this issue for all their users? For the record, I'm not against taking action, but I'd like to understand what is expected.

**Comment by Betree** [comment]
> For example, the confetti could be celebratory like it is on opencollective, where it should removed for users that prefer less motion. But it may also be used in a storyline, where for example a confetti cannon is used to fill a bucket of confetti. In this case, removing it entirely breaks the story in an unexpected way. The decision I make has to fit all use cases.

This is a very good point.

I went to see what others are doing:
- https://github.com/joshwcomeau/react-flip-move: found nothing
- https://github.com/wadackel/sweet-scroll: found nothing
- https://github.com/recharts/react-smooth: found nothing
- https://github.com/Popmotion/popmotion introduced an helper to check and conditionally disable animations based on `prefers-reduced-motion` (https://github.com/Popmotion/popmotion/issues/677 + https://github.com/framer/motion/pull/407).

In terms of developer experience, the solution I'd like to see would be to accept a special param in the options to disable the confettis when `prefers-reduced-motion` is set, ie:

```es6
confetti({ disableIfReducedMotion: true });
```

That way it wouldn't impact places where it's used to build a confetti cannon, but we would have an easy option to disable optional animations.

It may look out of scope for this project, so I would not be shocked if you prefer not to include it. The complexity of having that in our client codebase is ok, and we could argue that it's the responsibility of the projects using this library to do that check for all their animations. 

But we could also see it as an opportunity to encourage good practices - I personally wasn't aware that this could be an issue before @iliana reported this to us.

**Comment by catdad** [comment]
Since I am making confetti this easy, I do feel some responsibility in letting people know that confetti are not always great. I added a new `disableForReducedMotion` option to handle this automatically. I also added a note to the readme, because I think it's reasonable to make developers aware of this sort of thing.

Version 1.2.0 is going through CI now and will be out shortly.

**Comment by Betree** [comment]
Awesome @catdad, thanks for your super fast answer on this 💪
