### ISSUE TITLE
Configure particle size

### ISSUE THREAD

**Issue by ComedyTomedy** [catdad/canvas-confetti#116]
This is excellent, but I'd like MUCH bigger confetti pieces ☺

Could we maybe have a `size` parameter to scale them?

Or is there a way to do this already? Perhaps a hack with a small user-defined canvas, and then scale it up? (I've never used canvas, so I have no idea if that even makes sense!)

**Comment by ComedyTomedy** [comment]
Having poked around a bit - circles already have `ovalScalar`, which could be exposed as `opts.scale`. Having set `shapes` to `['circle']` and increased the `ovalScalar from 0.6 to 2, that looks fine to me ☺

The challenge is getting squares to scale at the same rate, while also scaling their fluttering.

**Comment by catdad** [comment]
It's not that obvious in the code, but all confetti size is controlled by how far they are allowed to wobble. You can [change the size of all confetti equally like this](https://github.com/catdad/canvas-confetti/blob/5d743a1f022b8c0d1d6f51b09f0afda3609296c2/src/confetti.js#L307-L308).

Something doesn't look quite right though if you go too big (say, setting the scale to `5`), which tells me something isn't quire right about all that math. I want to play around with it a bit more to figure out why that is

**Comment by ComedyTomedy** [comment]
OH! That makes total sense! I'd been changing everything BUT the wobble. I'll stick with a hacked codebase for now, and keep an eye on any future developments ☺ No pressure.

Thanks for taking an interest and helping ♥

**Comment by catdad** [comment]
This has been released in v1.3.0
