### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by littlefinger1** [catdad/canvas-confetti#118]
Can we expect react native support anytime?

**Comment by catdad** [comment]
I'm a web developer and this is a web component. So the immediate answer is no. Web components are generally not React Native components.

In theory, it might already with with something like [`react-native-canvas`](https://github.com/iddan/react-native-canvas) and [`confetti.create`](https://github.com/catdad/canvas-confetti/blob/master/README.md#confetticreatecanvas-globaloptions--function). I have not tried it though and can't really promise anything.

If you are interested in contributing to make React Native work, let me know.
