### ISSUE TITLE
[GENERAL] Create a dedicated demo folder

### ISSUE THREAD

**Issue by edoardolincetto** [catdad/canvas-confetti#123]
Updating the demo, according to an issue already open, I found it uncomfortable to work in a single `.html` file, also containing `.css` and `.js`. I'm available to create a pull request to split the file into a new `style.css` and `app.js` and create a dedicated folder for them; I think the result will be cleaner.

**Comment by catdad** [comment]
Thanks for the suggestion! However, I am not sure that this page is large or complicated enough to justify doing this just to "make it cleaner". And in fact, there is really nothing wrong with html, js, and css all in the same file. We have largely been taught wrong that we must always isolate these things. Limiting external resources being loaded makes loading and renders faster, and I would hesitate unnecessarily splitting anything out unless there is a lot more code to deal with
