### ISSUE TITLE
Confetti from a certain element

### ISSUE THREAD

**Issue by KTibow** [catdad/canvas-confetti#129]
If you want confetti to blow out from a button, it'd be good to be able to pass an element.

**Comment by catdad** [comment]
I don't necessarily hate the idea of including this in the library. It is quite trivial to do with the current API though. I'll leave it open to see if there's any interest.

**Comment by fungiboletus** [comment]
I did something like this:

```javascript
function confettiFromElement(element, opts) {
  const { top, height, left, width, } = element.getBoundingClientRect();
  const x = (left + width / 2) / window.innerWidth;
  const y = (top + height / 2) / window.innerHeight;
  const origin = { x, y };
  confetti({origin, ...opts)});
}
```

**Comment by KTibow** [comment]
@fungiboletus so does that mean that you just have to copy/paste that code in somewhere? Do you think the user should be able to provide offsets from the center of the element?

**Comment by catdad** [comment]
There appears to be no further interest in this. Since it is trivial to implement outside of this library (see previous code or [this codeed](https://codepen.io/catdad/pen/VwjRLoM), I will close this feature request for now. If there is interest in the future, it can be reopened.
