### ISSUE TITLE
Want to understand this movement principle

### ISSUE THREAD

**Issue by hua1995116** [catdad/canvas-confetti#141]
I want to understand the principle of this animation, is there any related article or explanation

**Comment by catdad** [comment]
Sorry, I don't think I understand the question. Can you clarify or be more specific?

**Comment by hua1995116** [comment]
I want to know about the principle of `updateFetti` movement, reading the code is a bit difficult to understand.

**Comment by hua1995116** [comment]
I know about the calculation of fetti.x and fetti.y, but I'm not sure how the deformation of the other three coordinates works when used as a square

**Comment by catdad** [comment]
Sorry, I don't have time right now to write up how animation works. Hopefully you can respect that this is a very large and broad question that requires a lot of effort in explaining and teaching. It is not a casual question for an open-source project.

All the code is available for you to study. You should be able to Google "3D animation in 2D space" and find more information. 

I will close this but for now, as there is no actionable item here.
