### ISSUE TITLE
License text does not appear in the minified file served by the CDN

### ISSUE THREAD

**Issue by dopatraman** [catdad/canvas-confetti#143]
Should I make a PR with it?

**Comment by catdad** [comment]
The license does not need to be contained in the minified file. Not only is it not necessary, but it also a waste of bandwidth. The license is [already distributed alongside the rest of the files in the CDN](https://cdn.jsdelivr.net/npm/canvas-confetti@1.3.3/LICENSE) and does not need to be copied within each file individually. Thanks for asking!

**Comment by dopatraman** [comment]
right now, I am pulling the LICENSE file from the CDN via a script tag. Are you aware of whether that fulfills the attribution requirements?
