### ISSUE TITLE
Feature Request: Raining down confetti

### ISSUE THREAD

**Issue by nh916** [catdad/canvas-confetti#144]
I saw this on salesforce trailhead learning platform and it is the coolest thing. Basically whenever a user completes any learning path a confetti rains down for them and it is just the coolest thing ever. The confetti looks very similar to this package and I was wondering if that is a feature that you would want to implement.

**Comment by catdad** [comment]
I am not familiar with the salesforce learning platform. Can you describe more what the actual confetti looks like there? Maybe even provide an image or a gif?

You already can make the confetti just fall straight down. You can see it [in the snow demo](https://www.kirilv.com/canvas-confetti/#snow). Is that not what you mean?

**Comment by nh916** [comment]
It is similar to the snow but very slightly different. I took a video of it and linked it below

https://imgur.com/a/DI4yoJm

**Comment by catdad** [comment]
Okay, so there are a few things going on. Here's a breakdown:

|| Description || Status || Note ||
| confetti simply falling down | ✔ | `startVelocity: 0`, `{ origin: { y: 0 }}` |
| confetti falling down at different speeds | ✔ | `gravity` |
| confetti are different sizes | ✔ | `scalar` |
| confetti are different shapes (I only see square and circle) | ✔ | `shapes: ['circle', square'] |
| some confetti drift left/right | ❌ | existing request !99 |

Did I miss anything? It seems like this would be pretty easy to add

**Comment by catdad** [comment]
I have not finished up `drift` just yet, but I created [this quick codepen](https://codepen.io/catdad/pen/rNWrEGd) to show what the complete effect might look like. It might need a bit more fine tuning depending on how close exactly you want it to the video shown.

**Comment by nh916** [comment]
That is beautiful! Thank you so much!

**Comment by catdad** [comment]
Published in 1.4.0
