### ISSUE TITLE
I need help figuring out how to remove the code that is displayed

### ISSUE THREAD

**Issue by Joshii01** [catdad/canvas-confetti#146]
Hello there @catdad ! i currently want to hide the code under the description of the confetti cannon, but i do not know how to do so without breaking the whole thing. can you please help me? thanks! <3
![image](https://user-images.githubusercontent.com/78946868/112358468-9bf90e00-8c8d-11eb-9e7e-0e9b12b45931.png)

**Comment by catdad** [comment]
I am confused. You want to hide the code on my demo website? This website is a demo of the library, not the library itself, and it intends to let developers experiment with the library. You can't change how my demo works.

**Comment by Joshii01** [comment]
no, that is not the demo website. i have it on another website to run the code and mess with it/figure it out right now

**Comment by Joshii01** [comment]
The website that i used to run the code is called <a href=repl.it>replit</a> and heres a link to the <a href=https://canvas-confetti.sulaimanahmed1.repl.co>confetti cannon </a>

**Comment by catdad** [comment]
Maybe I am still confused? So you have copied the demo website to a different domain. And now you are trying to do something with that demo website? I am not sure what your question is. Are you having trouble using the library or understanding the documentation?

**Comment by Joshii01** [comment]
yea, i just want to make the code under the description hidden so like it wont show

**Comment by Joshii01** [comment]
like this code here: 
![image](https://user-images.githubusercontent.com/78946868/112392147-31a89380-8cb6-11eb-9541-77ee72abac28.png)

**Comment by catdad** [comment]
Maybe I am wrong, but this seems like a request for general help on how to build your page, and not an issue with this library? I am not sure I have time for that at this time. For now, I will close this. If you do have an issue with using this library, can you please provide more details on that issue and I will reopen the issue?
