### ISSUE TITLE
Docs: How to position the canvas.

### ISSUE THREAD

**Issue by guettli** [catdad/canvas-confetti#148]
In the example you add the canvas to the end of the page.

In my case this was far too low.

Please add a section in the README about how to position the canvas.

I published my version here: https://stackoverflow.com/questions/67107077/htmx-load-js-lib-and-execute-function

**Comment by catdad** [comment]
I am not sure I understand your question. Can you provide a clear description of the problem you are having with this library, or even include repro code for the issue you are having.

From the link, it looks like might be using a custom canvas. In which case, it is really not up to this library to explain how to position it. It is positioned like any other element on a web page, and the exact way to do it depends on your exact needs, the exact page you are building, the exact libraries you are using to build your page, and personal preferences (that is to say, this is general application development and not a concern of this library).
