### ISSUE TITLE
How to remove the canvas after it has finished?

### ISSUE THREAD

**Issue by guettli** [catdad/canvas-confetti#149]
I want to remove the canvas after the animation has finished. How to do this?

Background: In my case the canvas does not resize automatically although I use `resize: true`.

The canvas seems to be above my buttons, so that it is no longer possible to click these buttons.

This is no problem, I just want a callback after the animation has finished, so that I can remove the canvas at the end.

**Comment by catdad** [comment]
Can you tell me more about how you are using the library?

When using the default canvas, it is automatically removed after the animation is done. It will also set CSS to make sure that the canvas is click-through and doesn't block interactions with elements below it.

Are you using a custom canvas?

In all cases, firing confetti returns a promise, so you can `.then` it to wait for the promise to complete.

**Comment by guettli** [comment]
> In all cases, firing confetti returns a promise, so you can .then it to wait for the promise to complete.

Thank you for this hint. This was not cleat to me.
