### ISSUE TITLE
Why couldn't use a jo.org subdomain?

### ISSUE THREAD

**Issue by georgebawesome** [catdad/canvas-confetti#152]
## This is:
- Feature request

I have seen many frameworks using js.org subdomain. Why don't you use something like confetti.js.org instead of https://catdad.github.io/canvas-confetti/

**Comment by georgebawesome** [comment]
Sorry, I really mean js.org in issue title.

**Comment by catdad** [comment]
This is not related to the library. The demo page is hosted where I want it to be. And more importantly, it is a demo and not the library.
