### ISSUE TITLE
Support for React.js

### ISSUE THREAD

**Issue by prince272** [catdad/canvas-confetti#156]

**Comment by catdad** [comment]
Can you please add a description for what you are asking for? There is nothing inherently unsupported about React that I am aware of.

**Comment by prince272** [comment]
The question is "how to use this awesome library with react". React uses functional components.

**Comment by prince272** [comment]
Oh. Sorry for opening this issue. I just realized that your library  canvas-confetti is just a function which needs to be invoke to show the canvas-confetti. Thanks for your previous comment. You know, I've been searching and testing so many without understanding how they really work.

**Comment by prince272** [comment]
We can close the issue know i guess.
