### ISSUE TITLE
Circles without the tilt and wobbling

### ISSUE THREAD

**Issue by danielbrodin** [catdad/canvas-confetti#157]
Hi,

Is it possible to get the circle shape but without the tilt and wobbling and instead have different sizes on the shapes to mix it up a bit?

**Comment by catdad** [comment]
I have no immediate plans to add more shapes, but this is a good idea. I will leave this feature request open in case someone is interested in contributing.

**Comment by catdad** [comment]
The `flat` option was released in version 1.7.0, allowing tilt and wobble to be disabled.
