### ISSUE TITLE
Uncaught TypeError: confetti is not a function

### ISSUE THREAD

**Issue by lastnoob** [catdad/canvas-confetti#158]
I'm trying to get a basic codepen to work just to get started with the project, but it returns an error. I've tried basically everything I could from the docs, but I must be doing something wrong.

`Uncaught TypeError: confetti is not a function`

https://codepen.io/simii/pen/poeGQQx

Could you please point me to the right direction on how to get started?

Thank you!

**Comment by catdad** [comment]
Hi @lastnoob 

Based on the example, I will assume you are new to web development. Welcome!

This, like pretty much every library you find, will not be automatically available in the browser. They need to be referenced in some way in your application in order for them to be available. This of this like installing programs on your computer. On the web, this is generally done by including a `script` tag on your web page, though more advanced techniques are also available.

You can [check out the Install section of the readme](https://github.com/catdad/canvas-confetti#install) to find out more about this project. The easiest way to get started is to include this bit of code inside the `html` of your application:

```html
<script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.4.0/dist/confetti.browser.min.js"></script>
```

Please also do keep in mind that this project is not a course in beginner web development, and this issue tracker is not a place for general learning. General questions like this are better suited to educational material that you should be able to readily find elsewhere on the internet.
