### ISSUE TITLE
Can you add more shapes?

### ISSUE THREAD

**Issue by bdthemes** [catdad/canvas-confetti#163]
Thanks for this script. Can you add more shapes in your script? 

for example, look here: 

https://kit-creations.web.app/confettiKit/

**Comment by catdad** [comment]
I have no immediate plans to add more shapes, but this is a good idea. I will leave this feature request open in case someone is interested in contributing.

**Comment by catdad** [comment]
I know it has been a minute, but there are now more shapes. Infinite shapes, actually.

2 helpers were added:
* `shapeFromPath`: this lets you create any shape you want using an SVG path string.
* `shapeFromText`: this lets you add emoji confetti (and other text, but that's not interesting).

In both cases, your options are limitless and it does not require for a shape to be added to the library itself. Both of those are available in the latest version: 1.9.0.
