### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by jonlivingston** [catdad/canvas-confetti#173]
[This package](https://www.jsdelivr.com/package/npm/canvas-confetti) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by catdad** [comment]
This was a regression in 1.5.0 related to the CI changes. I have now published 1.5.1 to correct this.

While I see the importance of this, it is vital for all users to not rely on automatically resolving versions and files in a CDN. Instead, applications in production should always reference the exact file in the exact version of the library that they need to include.
