### ISSUE TITLE
I can't believe you haven't made a "make it rain" 💵  one yet, 😂 🤣 good stuff though man.  Best I've seen yet, good job.

### ISSUE THREAD

**Issue by dthomason** [catdad/canvas-confetti#175]
Oh a feel free to delete this non issue 👍🏼

**Comment by shstkvch** [comment]
Just to add, I think this plugin is awesome. Great work catdad

**Comment by catdad** [comment]
I'm glad you're enjoying this module!

In case you are interested in emoji, I did try it (see #82) and found the performance is not acceptable to be included in this module.
