### ISSUE TITLE
Help instantiate confetti through NPM

### ISSUE THREAD

**Issue by bboy-space** [catdad/canvas-confetti#177]
Hello,
Project looks awesome, but probably a noob question I can't make it work with your explanations !
I included it though NPM (don't want the CDN file) because i pack all my JS for prod.

Here is my very basic code : 

`const confetti = require('canvas-confetti');

$("#test").click(function () {	
	    confetti({
		    particleCount: 100,
		    spread: 70,
		    origin: {y: 0.6}
	    });
		return false;
});
`
==> 'Uncaught TypeError: confetti is not a function'

I read that confetti function is only for CDN and not for NPM install, but I don't know how to instantiate because I only have avaiable the following methods : 
- call
- create
- reset
- bind

Doing call and bind triggers an error and calling create requires a canvas... and i don't know a canvas. 

Thanks for help instantiating the confetti.
++

**Comment by catdad** [comment]
Can you provide more information on how to reproduce this issue? Do you have a small retro you can share? What bundler are you using?

**Comment by bboy-space** [comment]
Hmm, maybe that was not clear. My question is more : "What code would you write to launch confetti when a user clicks on a specific button ? "

I am using webpack to build my JS. So i did 

`"npm install --save canvas-confetti", `

then i added this in my JS file 
`"const` confetti = require('canvas-confetti');"`

and after that step I am stuck. Because if i use the code that is shown as example , it triggers a  "confetti is not a function" in the browser console : 
`confetti({
     particleCount: 100,
     spread: 70,
     origin: {y: 0.6}
});`

As I am including the library from npm and require, the confetti function is undefined so i don't know how to use it.

Here are 2 captures of the code. The first one is the real code from my editor, and the 2nd is the code visible in the browser, and there you can see that the confetti library is correctly include with webpack.

![Capture d’écran 2022-03-09 103659](https://user-images.githubusercontent.com/5296748/157414527-67ba38c4-a1da-408a-a162-d1840a6d15d4.png)

![Capture d’écran 2022-03-09 103151](https://user-images.githubusercontent.com/5296748/157414241-cdf9e8cf-9c80-4f59-8a61-4ba5606407d6.png)

**Comment by catdad** [comment]
This is generally a webpack issue. Webpack will always prefer importing ES Modules (you can see the file mapped in devtools is `confetti.module.mjs`), regardless of how you are including the code in your project. It has its reasons but it can be confusing.

What webpack would prefer you to do is use modern syntax, like:

```js
import confetti from 'canvas-confetti';
```

If you want to use `require`, you will need to get the default export form the module;

```js
const confetti = require('canvas-confetti').default;
```

**Comment by bboy-space** [comment]
GENIUS ! 
I didn't even know that. Thanks for the tip, now is working doing as suggested :

`import confetti from 'canvas-confetti';`

cheers ++

**Comment by joshlewis** [comment]
That `.default` at the end would be really helpful to have in the README.md.
