### ISSUE TITLE
Upon fresh installation I get: confetti is not a function

### ISSUE THREAD

**Issue by Stophface** [catdad/canvas-confetti#179]
I installed this library with

    yarn add canvas-confetti

I see it in my `package.json`

    "canvas-confetti": "^1.5.1"

In my `react component` I do the following 

    const confetti = require('canvas-confetti');
    confetti();

And it gives me

> Uncaught TypeError: confetti is not a function

Why is that?

**Comment by theweiweiway** [comment]
same here

**Comment by theweiweiway** [comment]
it worked after i did 

`import confetti from "canvas-confetti";`

```
      confetti({
        particleCount: 100,
        startVelocity: 30,
        spread: 360,
        origin: {
          // since they fall down, start a bit higher than random
          y: 0.25,
        },
      });
```

**Comment by Stophface** [comment]
@theweiweiway Thats it. The documentation needs updating!
