### ISSUE TITLE
How to draw custom confetti particles using canvas?

### ISSUE THREAD

**Issue by jahirfiquitiva** [catdad/canvas-confetti#180]
Is there a function that received the canvas or its context as a parameter and allows to draw custom confetti particles?

Similar to https://github.com/alampros/react-confetti#drawshape= ?

If there's no function, could you please allow something like that? (I prefer using this lib)

Thanks in advance.

**Comment by catdad** [comment]
There is no option to do this and I have no plans on adding one. There would be a significant amount of complexity due the web worker. If you are happy with `react-confetti`, I would suggest using that module instead since it provides the functionality you need.
