### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'reset')

### ISSUE THREAD

**Issue by jahirfiquitiva** [catdad/canvas-confetti#182]
Hi, I'm getting this error with version `1.5.1`

`Uncaught TypeError: Cannot read properties of undefined (reading 'reset')`

Would you mind looking into it? Thanks!

![Shot 2022-06-14 at 18 30 29@2x](https://user-images.githubusercontent.com/10360816/173705981-3e060b7e-43ac-4f6a-9d71-9495bacfc35b.png)

**Comment by catdad** [comment]
Hey, sorry for the delay. Can you please provide more context? What did you do to get this error?

**Comment by catdad** [comment]
This may or may not be fixed in 1.6.0. However, since this bug is stale, I am closing it.
