### ISSUE TITLE
confetti z index

### ISSUE THREAD

**Issue by strapidinnovation** [catdad/canvas-confetti#196]
i have set my modal background z index as 100 and modal content z index 200, how can i make confetti appear Infront of background but behind content, setting z index in confetti object to 150 does not work

**Comment by strapidinnovation** [comment]
nevermind i solved it

**Comment by mtayyabmakki** [comment]
@strapidinnovation  how did you solve kindly share

**Comment by strapidinnovation** [comment]
@mtayyabmakki you need a canvas with absolute position and z index 150 and then you can do this

```javascript
var canvas = document.getElementById('my-canvas');

// you should  only initialize a canvas once, so save this function
// we'll save it to the canvas itself for the purpose of this demo
canvas.confetti = canvas.confetti || confetti.create(canvas, { resize: true });

canvas.confetti({
  spread: 70,
  origin: { y: 1.2 }
});
```

**Comment by kdb13** [comment]
@strapidinnovation I am trying to display the confetti on top of an HTML5 `<dialog>` element. I tried setting the `z-index` to a higher value but still the confetti is showing behind the dialog.
