### ISSUE TITLE
大家项目在引入canvas-confetti后，项目有没有加载卡顿、非常缓慢的问题？

### ISSUE THREAD

**Issue by LiuYuYang01** [catdad/canvas-confetti#198]
大家项目在引入canvas-confetti后，项目有没有加载卡顿、非常缓慢的问题？如果有的话是如何解决的？

**Comment by catdad** [comment]
Sorry, I don't speak Chinese, but Google Translate suggests that this is a duplicate of #199, which makes sense. I will close this, so that any necessary conversation can happen in just one issue.
