### ISSUE TITLE
Not A Proper Text Alignment Of The Emoji And It's Text

### ISSUE THREAD

**Issue by kratin01** [catdad/canvas-confetti#204]
issue Description:
The emoji in the text description is not properly aligned. Which Look Very Odd.

Issue Screenshot
![pic 1](https://github.com/catdad/canvas-confetti/assets/140265041/d74f9d3a-a6ab-42b3-86bb-392498f132e8)

![pic 2](https://github.com/catdad/canvas-confetti/assets/140265041/6994070c-22bc-43ca-ae68-2e56ca7bffdd)
![pic 3](https://github.com/catdad/canvas-confetti/assets/140265041/a9822461-6f98-4139-8c22-f6c138d05f43)

Steps to Reproduce:

Navigate to (https://www.kirilv.com/canvas-confetti/)
Look for the text containing the emoji.
Observe that the emoji is not aligned correctly within the text.
Expected Behavior:
The emoji should be properly aligned within the text, ensuring a visually appealing and correct display.

Actual Behavior:
The emoji is not properly aligned within the text, causing a visual misalignment.

**Comment by catdad** [comment]
The text is in the center. It is supposed to be in the center and it is in the center. I am not sure what you mean.

**Comment by kratin01** [comment]
in my humble opinion, there seems to be a slight misalignment between the emoji's text and the code below, which could potentially cause confusion. To address this, I would like to suggest centering the emoji's text in relation to the div below, which should improve the overall visual coherence of the text.
![Screenshot (25)](https://github.com/catdad/canvas-confetti/assets/140265041/0fbefb14-d4fa-4ebc-bf9e-51d7d18674a7)

**Comment by catdad** [comment]
The text you circled is centered and will remain centered.
