### ISSUE TITLE
`shapeFromPath` type missing on `@types/canvas-confetti`

### ISSUE THREAD

**Issue by evadecker** [catdad/canvas-confetti#215]
It looks like TypeScript types for this project may not be officially maintained, so if this is the wrong place to report, let me know.

The `confetti` type is missing types for `shapeFromPath`. `shapeFromText` is also missing.

<img width="490" alt="image" src="https://github.com/catdad/canvas-confetti/assets/4117920/959d2510-c35d-4dc2-a413-0afff9dda70f">

**Comment by evadecker** [comment]
I opened a PR to add these types to `DefinitelyTyped`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67500

**Comment by evadecker** [comment]
Types merged 🤘

**Comment by catdad** [comment]
This project has no TypeScript definitions. If you have found definitions somewhere, they are not from me, they are not maintained by me, and neither I nor my library have any affiliation with those defections. Feel free to file an issue wherever you found those definitions!
