### ISSUE TITLE
Calling shapeFromText throws an error if OffscreenCanvas is not supported

### ISSUE THREAD

**Issue by pavle-goloskokovic** [catdad/canvas-confetti#219]
Calling `shapeFromText` throws an error if `OffscreenCanvas` is not supported. Observed on iPhone 6.

Is it possible to check if `OffscreenCanvas` is supported, and in case it is not use regular `canvas` element as fallback to generate bitmap data? Or at least fail gracefully so that this error does not break the app.

Thanks!

**Comment by catdad** [comment]
I understand what you are asking and why you are asking it. However, iOS 12 and Safari 12 are **very** old. For a single-developer free and open source project, asking to support such old browsers is extremely cumbersome. It is a lot of work, prohibits adding many new features, and will affect next to no users while placing huge burden on the developer. I simply don't have that kind of time.

And I know, you might think "what if I contribute that in a PR, it sounds simple"... do understand that that still leaves me to **continue** supporting a very outdated browser afterwards. (It's also worth mentioning that `ImageBitmap` was added in Safari 15, so the feature would never be able to be implemented anyway.)

I will not be working on this, and neither should anyone else.

**Comment by pavle-goloskokovic** [comment]
Makes sense, thanks for considering.

**Comment by Hunternif** [comment]
Hi! Just wanted to flag that I ran into this issue on iPad OS 15.4.1 as well. Implemented the check for `OffscreenCanvas` in my app as suggested here: https://stackoverflow.com/questions/56884685/check-support-for-offscreen-canvas

**Comment by evnp** [comment]
Really appreciate the awesome library!

Just wanted to mention that we're currently observing this issue in Safari 15:

<img width="1440" alt="Screen Shot 2024-10-11 at 8 38 54 AM" src="https://github.com/user-attachments/assets/8f2a5f3b-727b-430b-9e2c-ee9ea2df789c">

*15.6.1 (17613.3.9.1.16)

**Comment by wesbos** [comment]
Also seeing this error in Safari 15.x in the `function shapeFromText(textData) {` 

Seems to work with all demos except the `confetti.shapeFromText(` 

<img width="820" alt="Screenshot 2024-11-27 at 11 09 28 PM" src="https://github.com/user-attachments/assets/39edd7c1-a2b4-45ed-b62e-06b4dbe34f07">
