### ISSUE TITLE
rerun the animation on stateChange.

### ISSUE THREAD

**Issue by smaniren** [catdad/canvas-confetti#225]
Hi!

Maybe i've overseen something. I'm trying to rerun the animation everytime my form submits.
this is the setup i use:

```
import Realistic from "react-canvas-confetti/dist/presets/realistic"

const onSubmit = async (values: NewItemSchemaType) => {
  setConfetti(false)
  await fetch('path',{
    method: 'POST',
    body: formData
  })
  .then(async response => {
    setConfetti(true);
  })
}
```

The confetti is only created the first time i'm submitting my form.

How can i run the animation every time the form gets submitted?

**Comment by andreaselia** [comment]
Where's the rest of the code? Could you create a CodePen or something?

**Comment by catdad** [comment]
The `react-canvas-confetti` repo is [here](https://github.com/ulitcos/react-canvas-confetti), and it is not maintained by me. If you have an issue with that library, please log it on that repo.
