### ISSUE TITLE
Sponsorship in exchange for ad space?

### ISSUE THREAD

**Issue by ben519** [catdad/canvas-confetti#226]
Hey, I use `canvas-confetti` for my platform [Scipress.io](https://www.scipress.io/). I was hoping I could sponsor this project in exchange for advertising my company on your README. I want to advertise my site, but I also want to say thanks for creating and maintaining this package!

Let me know if this is possible and what it would entail. Thanks!

**Comment by catdad** [comment]
Hi @ben519. Thank you so much for your support! I did some research and asked around, and ended up opening up some advertisement tiers on my [sponsors dashboard](https://github.com/sponsors/catdad). Feel free to participate based on the information there, and please let me know if you have any questions.

**Comment by catdad** [comment]
No worries. I'm glad you're getting use out of this library!
