### ISSUE TITLE
canvas.transferToImageBitmap is not a function

### ISSUE THREAD

**Issue by yuxxeun** [catdad/canvas-confetti#232]
I got this error message when using `canvas-confetti` package, any idea?

![image](https://github.com/catdad/canvas-confetti/assets/50067865/512e3d15-21ca-4294-8292-dc50a11e4b27)

**Comment by Zatheos** [comment]
I believe it's invoking this method 👇
[https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/transferToImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/transferToImageBitmap)
Possibly a problem with your code environment, or perhaps your `canvas` variable isn't actually a canvas at this point, if you've changed the source code?

**Comment by yuxxeun** [comment]
Thanks for your response @Zatheos 
Now, its works. But suprisingly i dont know why, maybe its becasue I'm try to install the dependencies with `bun` and `yarn` (?).
End up with trying to re-clone from repositories and install all dependencies with `npm i --legacy-peer-deps`, and works.
