### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by SeeSharpSoft** [catdad/canvas-confetti#50]
Hi,

can you please provide a license file or state under which license this project is published. Thanks and keep up the good work!

**Comment by catdad** [comment]
License is already present in [package.json](https://github.com/catdad/canvas-confetti/blob/941551e799a1f3f33affb8a2c837c2be6ed1f2ba/package.json#L22) and shows up on the [npm](https://www.npmjs.com/package/canvas-confetti) and [jsdelivr](https://www.jsdelivr.com/package/npm/canvas-confetti) pages.

Let me know if there's anything else you need.

**Comment by catdad** [comment]
I have no plans to change anything. See my previous comment about the license.
