### ISSUE TITLE
NodeJS Support

### ISSUE THREAD

**Issue by Morb0** [catdad/canvas-confetti#59]
How about add nodejs [canvas](https://github.com/Automattic/node-canvas) support?

**Comment by catdad** [comment]
What is the benefit of adding this? What are you trying to accomplish?

**Comment by 0ArturkA** [comment]
I try render gif animation in canvas on server.

**Comment by catdad** [comment]
Sorry, I am away right now so I can't validate this, but it looks like you can use `node-canvas` through `jsdom`: https://github.com/jsdom/jsdom#canvas-support

Let me know if you have any issues with this or have any specific code you are struggling with.
