### ISSUE TITLE
Question - Updates

### ISSUE THREAD

**Issue by VaclavElias** [catdad/canvas-confetti#66]
Hi,

Is it possible to include to your releases, a summary what's new and what's changed?

E.g. like they are doing it here

![image](https://user-images.githubusercontent.com/4528464/64356916-941a4000-cffb-11e9-80bf-38dc2b6731e3.png)

Thank you  :)

**Comment by catdad** [comment]
I wouldn't mind doing that. I do that for my bigger projects, but this one started out just for fun.

I can start doing that for new releases, bug I am not sure when I would have time to go through the old ones and add updates. If you want to look at the compare pages for all the releases and put together something, I'm happy to post it.

**Comment by VaclavElias** [comment]
Thank you Kiril. 

This is very good project. I think let's start from now on and I guess just a brief summary / break changes would be nice to be aware of. No need to spend too much time on this.

I will try to list the previous changes for you if I am going to understand them :).

Thanks!

**Comment by catdad** [comment]
I've added release notes going all the way back to 0.0.3, which can just be considered as the de-facto first release.

**Comment by VaclavElias** [comment]
Thank you, this is great! :)
