### ISSUE TITLE
How to use this confetti in Angular 4 

### ISSUE THREAD

**Issue by santhanakrishnanstark** [catdad/canvas-confetti#67]
Hi guys ! 
    I install this canvas-confetti using npm install.. after that i dont have an idea to use this in my angular project.
    how can i import this ?

**Comment by santhanakrishnanstark** [comment]
@danielkuhlwein It worked man ! thanks

**Comment by sommmen** [comment]
This pops up when googling, so for other people, this is how i got it working in Angular v14 (In 2022);

Run

`npm install canvas-confetti`

For good practice, we'll drop this in an angular service.
Drop the following basic service in your project:

``` ts
import { Injectable } from '@angular/core';
import confetti from 'canvas-confetti';

/*
    Shows confetti animations, just for fun.
    See: https://www.kirilv.com/canvas-confetti/
*/
@Injectable({
    providedIn: 'root'
})
export class ConfettiService {

    constructor() { }

    public canon(): void {
        confetti({
            angle: this.randomInRange(55, 125),
            spread: this.randomInRange(50, 70),
            particleCount: this.randomInRange(50, 100),
            origin: { y: 0.6 }
        });
    }

    private randomInRange(min, max) {
        return Math.random() * (max - min) + min;
    }
}
``` 

Don't forget to declare the service in your module!

``` ts
    providers: [
        ConfettiService
    ]
```

Use in your component:

``` ts
import { ConfettiService } from '<MyModule>/services/confetti.service';
...
constructor(private confettiService: ConfettiService) { }
...
// Some function somewhere:
this.confettiService.canon();
```

Use in the same module or import the module of the confetti service of course.

Maybe add this to the readme or something?

**Comment by keyboardbreaker** [comment]
@sommmen solution solved my problem.

i also had to add this flag to my tsconfig.json
`  "compilerOptions": {
    "allowSyntheticDefaultImports": true
  },`

**Comment by abu18saud** [comment]
Hi Mr. @danielkuhlwein I need to create confetti above my button, how that?
