### ISSUE TITLE
Broken in older versions of iOS Safari (v. 9.0)

### ISSUE THREAD

**Issue by danielkuhlwein** [catdad/canvas-confetti#68]
Broken in older versions of iOS Safari (and probably other browsers) that don't support ECMAScript 6 features such as `let`.

Throws the following error:
![Screen Shot 2019-09-12 at 10 54 49 AM](https://user-images.githubusercontent.com/6547750/64806415-5748ce80-d550-11e9-8258-b59f1b9c5591.png)

---

I was able to fix this issue by simply changing 'let' to 'var' in `confetti.module.mjs`:

OLD
```
export let create = module.exports.create;
```

NEW
```
export var create = module.exports.create;
```

**Comment by catdad** [comment]
This has been fixed in 0.4.1. I still highly encourage using a build which will properly transform code to for the desired target browsers.
