### ISSUE TITLE
I need my confetti with in a particular div or component in angular 4 , How can i get that ?

### ISSUE THREAD

**Issue by santhanakrishnanstark** [catdad/canvas-confetti#70]
By default it covers entire viewport.

**Comment by santhanakrishnanstark** [comment]
I need my confetti with in a particular div or component in angular 4 , How can i get that

**Comment by catdad** [comment]
You can create your own instance of `confetti` in your own canvas: https://github.com/catdad/canvas-confetti#confetticreatecanvas-globaloptions--function

The last example on the [demo site](https://catdad.github.io/canvas-confetti/) also shows this scenario.

```javascript
// get a canvas that already exists on the page
var canvas = document.getElementById('custom-canvas');

var myConfetti = confetti.create(canvas, {
    resize: true
});

myConfetti({
    spread: 70,
    origin: {
        y: 1.2
    }
});
```

**Comment by santhanakrishnanstark** [comment]
@catdad  So that can i position the canvas element where i want right ? i will check

**Comment by catdad** [comment]
Correct, you can style your canvas any way you'd like. Take a look at [this demo](https://catdad.github.io/canvas-confetti/#custom-canvas) for reference.

**Comment by lavanyav0523** [comment]
but can I put a few html elements behind this canvas-confetti using this method?

**Comment by catdad** [comment]
You can do anything you'd like. It's your web page.
