### ISSUE TITLE
1.0.0 from CDN seems broken

### ISSUE THREAD

**Issue by ozramos** [catdad/canvas-confetti#94]
First I just want to say that this is an amazing library and the docs are very well done 🎊

However, I'm trying to get this to work on my site using the CDN but it doesn't seem to work with 1.0.0. Here are two super simple fiddles demonstrating this:

- Working with 0.5.0: https://jsfiddle.net/9q7rkc1m/
- Not working with 1.0.0: https://jsfiddle.net/9q7rkc1m/1/

Thanks!

**Comment by catdad** [comment]
Interesting. It looks like it's something in the jsdelivr minification process, and it works when you remove the `min` from the end. I'll look into it

**Comment by catdad** [comment]
I have a fix that I will publish shortly, but I also filed an issue for jsdelivr to document the obfuscation options so that we can test the result locally: https://github.com/jsdelivr/jsdelivr/issues/18185

**Comment by catdad** [comment]
Published in 1.0.1: https://jsfiddle.net/y0Lpf4um/
