### ISSUE TITLE
Upgrade 0.5.0 -> 1.0.0

### ISSUE THREAD

**Issue by VaclavElias** [catdad/canvas-confetti#95]
Hi,

Just some feedback. I am using confetti in Angular 8. When I run 0.5.0 it shows up on the full screen. No code changes were made on my side.

-  When I updated to 1.0.0 all confetti happens just in a small rectangle in the top left corner 300x 150. I fixed it by adding `undefined, { resize: true, useWorker: true }` to `confetti.create()`.
- I had to switch to `useWorker: false` as the UI became unresponsive, not sure why. I attached some screenshots of CPU.

**useWorker: false - after confetti fineshed**
![image](https://user-images.githubusercontent.com/4528464/71411943-3f9adf00-2643-11ea-9952-41fb8a403422.png)

**useWorker: true - after confetti fineshed**
![image](https://user-images.githubusercontent.com/4528464/71411967-56d9cc80-2643-11ea-967e-8beaa45492d3.png)

```ts
 showConfetti() {
    try {
      confetti.create(undefined, { resize: true, useWorker: false })({
          angle: this.random(20, 100),
          spread: this.random(50, 60),
          startVelocity: 80,
          particleCount: this.random(250, 350),
          ticks: 400,
          origin: {
            x: 0.2,
            y: 0.8
          }
        });
    } catch (e) {
    }
  }
```

**Comment by catdad** [comment]
Do you have a small sample application that reproduces this?

**Comment by VaclavElias** [comment]
Nope, that Angular application is big and it might be related with Angular. I might try to create just a test app in Angular and add confetti to see if the result is same. I might be able to do it in a few days or so.

**Comment by catdad** [comment]
That would be great! I don't have any experience with Angular, and so far, it has worked correctly in my test applications, as well as a React application I use it in. If you don't get to it, I can see if there is a template somewhere, but that probably won't be until after the holidays.

**Comment by VaclavElias** [comment]
Ohh, if you like javascript I recommend to play with TypeScript. You might like to rewrite confetti to TypeScript :) and Angular is then not far away from it. I like canvas-confetti library as it adds up some fun to boring websites. Also this one caught my eye https://auz.github.io/Bug/ but would prefer different kind of entities moving around and even following some path..

Let's see as the holidays is now here but will be in touch once I have my test app ready :)

**Comment by catdad** [comment]
I just tried the following:

```bash
ng new confetti-test
cd confetti-test
npm i -S canvas-confetti
npm start
```

I confirmed that this is using Angular 8 and canvas-confetti 1.0.0.

Then, I changed `src/app/app/component.ts` to include the following (I also tried some variations as well):

```typescript
import { Component } from '@angular/core';
import confetti, { create } from 'canvas-confetti';

const thing = create(undefined, { useWorker: true, resize: true });

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'confetti-test';
}

setTimeout(() => {
  confetti();
}, 1000);

setTimeout(() => {
  thing({
    angle: 90,
    spread: 60,
    particleCount: 350,
    ticks: 400
  });
}, 3000);
```

In both cases, the confetti were fullscreen and I did not see any significant CPU usage. I think something non-trivial is going on in your application that I am not sure how to reproduce.

**Comment by catdad** [comment]
Interesting... so I think I reproduced this just by using the demo page and pressing the snow button like 5 times quickly. then waiting until the confetti ends. I get this in the profiler (which is pretty tricky to capture actually):

![image](https://user-images.githubusercontent.com/2205537/71523968-694d4380-2899-11ea-96fa-88bd09c5a6b1.png)

While the synchronous work is not in the main thread, it is still for some reason blocking the main thread.

It looks like we get the callback triggered a whole lot (however it's in the worker?):

![image](https://user-images.githubusercontent.com/2205537/71523950-47ec5780-2899-11ea-84a6-d60782a538f7.png)

One thread points out A LOT of small tasks executing line 80 in the screenshot above.

**Comment by catdad** [comment]
Duh, I am an idiot. In the main thread version, there is only one Promise for as long as you keep firing more confetti. In the worker version, each confetti firing gets its own new Promise along with an inter-thread message to resolve that promise. However, no Promise is resolved until all confetti are done (i.e. as long as you keep firing, like in the snow demo, all Promises are help until every confetti finishes), so once done, it now has to resolve some 30,000+ Promises by sending 30,000+ inter-thread messages.

See #100 for this specifically. I should have that fixed shortly, so you can check if this is still an issue in your integration.

**Comment by catdad** [comment]
Version 1.0.2 has been published. Please take a look when you get a chance and let me know if you still see unresponsive UI issues.

**Comment by VaclavElias** [comment]
Thank you Kiril, I will test it and let you know. Yes, I forgot to mention there was some interaction before it became unresponsive.

**Comment by VaclavElias** [comment]
Ok, I have tested this new fix and so far I see no problems and I can use now `useWorker: true`.

Thanks for fixing this! :)

**Comment by catdad** [comment]
Thanks. I'll consider this closed then. If you find anything else or still have problems, definitely feel free to create another issue.
