### ISSUE TITLE
"Uncaught ReferenceError: i is not defined" with Chrome / webpack

### ISSUE THREAD

**Issue by momander** [catdad/canvas-confetti#97]
### Steps to reproduce

1. `npm install --save canvas-confetti`
1. Add `import confetti from 'canvas-confetti'` to one of your Javascript files.
1. In the same file, make a `confetti()` call.
1. Use webpack v4 to build the project in _production_ mode. (The error doesn't occur in _development_ mode).
1. Open the app in Chrome. (The error doesn't occur in Safari or Firefox).

### What happens

1. When opening the web application, Chrome shows this error message in the Javascript console: `Uncaught ReferenceError: i is not defined`
1. When the code makes the `confetti()` call, nothing happens and no new error message is shown.

### Code that throws the error

Below is the code that throws the error. The first `i.exports` statement makes Chrome display the error message. It's at the end of a ~5,900 character long line of minified code.

    var CONFETTI, SIZE = {}, module = {};
    [~5,900 characters omitted] return d.reset=function(){s&&s.reset(),i&&i.reset()},d}i.exports=x(null{useWorker:!0,resize:!0}),i.exports.create=x})(this, true, SIZE);
    onmessage = function(msg) {
      if (msg.data.options) {
        CONFETTI(msg.data.options).then(function () {
          postMessage({ callback: msg.data.callback });
        });

**Comment by momander** [comment]
You can see the error in my deployed app at https://wheelofnames.com/.

1. Make sure you use Chrome to access the web site, and keep your Javascript console open to see the error message which happens on page load.
1. Click the New item in the toolbar.
1. Click the wheel to make it spin.
1. When the wheel stops, there should be confetti fireworks, powered by `canvas-confetti`. It works in Safari and Firefox, but not in Chrome.

**Comment by catdad** [comment]
Is this happening in 1.0.0? This seems like the obfuscation error in #94. Can you try 1.0.1 that was released today?

**Comment by momander** [comment]
Version 1.0.1 fixed the problem. Thank you for your prompt reply, catdad, I really appreciate it!

I'm closing this issue now.
